account_id = "4b99fe044748e20b67286e12a4f239fb"
zone_id = "aa78e8cee3c1339cebb2e9b3dac10ca9"
compatibility_date = "2021-12-04"
type = "javascript"
workers_dev = false

name = "tooot-translate-development"
vars = {ENVIRONMENT = "development"}
kv_namespaces = [ 
  { binding = "LANGUAGES", id = "<ignored>" }
]

[env.candidate]
name = "tooot-translate-candidate"
route = "api-candidate.tooot.app/translate"
vars = {ENVIRONMENT = "candidate"}
kv_namespaces = [ 
  { binding = "LANGUAGES", id = "3d96a5a0bece43a1b8ad551505306716" }
]

[env.release]
name = "tooot-translate"
route = "api.tooot.app/translate"
vars = {ENVIRONMENT = "release"}
kv_namespaces = [ 
  { binding = "LANGUAGES", id = "b0196b4e1db04259aefaf599306afb7a" }
]

[build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
cache_persist = "./.mf/cache"
disable_cache = false
