account_id = "4b99fe044748e20b67286e12a4f239fb"
compatibility_date = "2023-08-17"
main = "./src/index.ts"

name = "tooot-translate-development"
vars = {ENVIRONMENT = "development"}
kv_namespaces = [ 
  { binding = "LANGUAGES", preview_id = "65df9e7d4fd740278104e7b6885bde05", id="65df9e7d4fd740278104e7b6885bde05" }
]

[env.candidate]
name = "tooot-translate-candidate"
route = { pattern = "api-candidate.tooot.app/translate", zone_name = "tooot.app" }
vars = {ENVIRONMENT = "candidate"}
kv_namespaces = [ 
  { binding = "LANGUAGES", id = "3d96a5a0bece43a1b8ad551505306716" }
]

[env.release]
name = "tooot-translate"
route = { pattern = "api.tooot.app/translate", zone_name = "tooot.app" }
vars = {ENVIRONMENT = "release"}
kv_namespaces = [ 
  { binding = "LANGUAGES", id = "b0196b4e1db04259aefaf599306afb7a" }
]
