account_id = "4b99fe044748e20b67286e12a4f239fb"
compatibility_date = "2021-12-04"
name = "tooot-push-candidate"
type = "javascript"
workers_dev = false
zone_id = "aa78e8cee3c1339cebb2e9b3dac10ca9"

durable_objects = {bindings = [
  {name = "TOOOT_PUSH_DEVICE_DEV", class_name = "Device"},
]}
vars = {ENVIRONMENT = "development"}

[env.candidate]
durable_objects = {bindings = [
  {name = "TOOOT_PUSH_DEVICE_CANDIDATE", class_name = "Device"},
]}
route = "api-candidate.tooot.app/push/*"
vars = {ENVIRONMENT = "candidate"}

[env.release]
durable_objects = {bindings = [
  {name = "TOOOT_PUSH_DEVICE", class_name = "Device"},
]}
name = "tooot-push"
route = "api.tooot.app/push/*"
vars = {ENVIRONMENT = "release"}

[build]
command = "yarn build"
[build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
cache_persist = "./.mf/cache"
disable_cache = false
durable_objects_persist = true
