account_id = "4b99fe044748e20b67286e12a4f239fb"
compatibility_date = "2023-08-17"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/index.ts"

name = "tooot-push-development"
vars = { ENVIRONMENT = "development" }
durable_objects = { bindings = [
  { name = "TOOOT_PUSH_DEVICE_DEV", class_name = "Device" },
] }
[[migrations]]
tag = "v1"

[env.candidate]
  name = "tooot-push-candidate"
  vars = { ENVIRONMENT = "candidate" }
  route = { pattern = "api-candidate.tooot.app/push/*", zone_name = "tooot.app" }
  durable_objects = { bindings = [
    { name = "TOOOT_PUSH_DEVICE_DEV", class_name = "Device" },
  ] }

[env.release]
  name = "tooot-push"
  vars = { ENVIRONMENT = "release" }
  route = { pattern = "api.tooot.app/push/*", zone_name = "tooot.app" }
  durable_objects = { bindings = [
    { name = "TOOOT_PUSH_DEVICE", class_name = "Device" },
  ] }
