name = "tooot-push-candidate"
type = "javascript"
account_id = "4b99fe044748e20b67286e12a4f239fb"
zone_id = "aa78e8cee3c1339cebb2e9b3dac10ca9"
compatibility_date = "2021-12-04"
workers_dev = false

route = "api-candidate.tooot.app/push/*"
vars = { ENVIRONMENT = "candidate" }
durable_objects = { bindings = [
    { name = "TOOOT_PUSH_DEVICE_CANDIDATE", class_name = "Device" }
  ] }

[build]
command = "yarn && yarn build"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.candidate]
vars = { ENVIRONMENT = "candidate" }

[env.release]
name = "tooot-push"
route = "api.tooot.app/push/*"
vars = { ENVIRONMENT = "release" }
durable_objects = { bindings = [
    { name = "TOOOT_PUSH_DEVICE", class_name = "Device" }
  ] }

[miniflare]
cache_persist = "./.mf/cache"
disable_cache = false
durable_objects_persist = true