account_id = "4b99fe044748e20b67286e12a4f239fb"
compatibility_date = "2021-12-04"
main = "./src/index.ts"
node_compat = true

name = "tooot-push-development"
vars = { ENVIRONMENT = "development" }
durable_objects = { bindings = [
  { name = "TOOOT_PUSH_DEVICE_DEV", class_name = "Device" },
] }
[[migrations]]
tag = "v1"

[env.candidate]
name = "tooot-push-candidate"
vars = { ENVIRONMENT = "candidate" }
route = "api-candidate.tooot.app/push/*"
durable_objects = { bindings = [
  { name = "TOOOT_PUSH_DEVICE_DEV", class_name = "Device" },
] }

[env.release]
name = "tooot-push"
vars = { ENVIRONMENT = "release" }
route = "api.tooot.app/push/*"
durable_objects = { bindings = [
  { name = "TOOOT_PUSH_DEVICE", class_name = "Device" },
] }
