name: Deploy tooot API services
on:
  push:
    branches:
      - candidate
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { package: ['push', 'translate'] }

    steps:
      - name: -- Step 0 -- Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
      - name: -- Step 2 -- Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: -- Step 3 -- Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          VERSION: ${{ github.sha }}
        with:
          wranglerVersion: '1'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ steps.branch.outputs.branch }}
          workingDirectory: './packages/${{ matrix.package }}'
      - name: -- Step 4 -- Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ matrix.package }}
        with:
          environment: ${{ steps.branch.outputs.branch }}
          sourcemaps: './packages/${{ matrix.package }}/dist'
          version: ${{ github.sha }}
